### ISSUE TITLE
Prevent/reduce page shift on popup when scrollbar appears

### ISSUE THREAD

**Issue by theotherstevenc** [email-markup-consortium/email-reader-view#13]

**Comment by M-J-Robbins** [comment]
@theotherstevenc I'm not currently seeing any shift 🤔
The scroll bar appears to be added inside the popup so there is no shift.
Could be an update in Chrome 111 'cos I'm pretty sure I saw it before 🤷

**Comment by theotherstevenc** [comment]
Weird, yeah 🤔🤔🤔

There is **no shift** on my personal laptop, using `Chrome 111.0.5563.64`. 

But, there _is_ on my SF laptop, using the same version, `Chrome 111.0.5563.64`:

<img src="https://user-images.githubusercontent.com/16547908/226059384-75cff5ad-4aed-47f8-8fdf-fe73b744065a.gif" width="400" alt="animation of the email reader view extension opening to demonstrate the affect of the scrollbar">

**Comment by theotherstevenc** [comment]
We can close this for now, and revisit when / if the shift returns
