### ISSUE TITLE
Launch 🍺

### ISSUE THREAD

**Issue by theotherstevenc** [email-markup-consortium/email-reader-view#18]
- [x] Research Chrome extension store
- [ ] Develop strategy plan for applying updates
- [x] List additional requirements for the launch

**Comment by M-J-Robbins** [comment]
[Publish in the Chrome Web Store](https://developer.chrome.com/docs/webstore/publish/)

I have set up a [Google developer account](https://chrome.google.com/u/1/webstore/devconsole/a21d7044-323f-4bec-9955-d865ea21d6d3/settings) under `emailmarkupconsortium@gmail.com`.

We can create a list of "trusted testers" 
> These test accounts allow you to make your application visible only to specific users for testing

I've added my google accounts and your's @theotherstevenc we can add more at any time.

Before we publish we need to
- [ ] Write a description (25 - 16,000 characters)
- [ ] We need to set up A link to the *privacy policy* for all extensions. The policy should include how data is collected, used, and disclosed.
- [ ] We need to create some screen shots (up to 5)
- [ ] Promo tiles 440x280 & 1400x560
- [ ] Potentially create a video 
- [ ] Write Permission justifications for each permission we request in the manifest `"permissions": ["storage", "activeTab", "scripting", "declarativeContent"],`

**Comment by M-J-Robbins** [comment]
We can create a video and gather screen shots once the add is finished and we are happy with it.
