### ISSUE TITLE
Outlook 365

### ISSUE THREAD

**Issue by husseinalhammad** [email-markup-consortium/email-reader-view#20]
Currently email clients are detected based on the current page's domain. For Outlook, `outlook.live.com` is what the extension currently looks for:

https://github.com/email-markup-consortium/email-reader-view/blob/324492339eaf66f780d60628cb673b5028c3ff2a/background.js#L56-L58

However, for Office 365 customers the domain is different: `outlook.office.com`

**Comment by theotherstevenc** [comment]
Are there steps to recreate this @husseinalhammad? 

I have a **Office 365** account, but do not see that domain when I access Outlook from the App launcher.

**Comment by husseinalhammad** [comment]
I have an Office 365 account too. I use the web version (installed as a PWA); not the desktop app.

- Go to office.com
- Login with an Office 365 account 
- Open Outlook from the app list
