### ISSUE TITLE
User-friendly settings

### ISSUE THREAD

**Issue by husseinalhammad** [email-markup-consortium/email-reader-view#4]
Assuming the target audience is not web developers, the current settings are probably not friendly to the average person.

For example, the value `1.25rem` is probably not going to mean anything to many people. Toggle options like "block images" probably do not to list a boolean value there.

I think the point I am trying to make it is the settings interface needs rethinking. It may be a matter of rewording things, but I think it's also worth considering updating the interface all together to improve to something you'd expect to see in the average app:

![twitter-display-settings](https://user-images.githubusercontent.com/8544092/193232385-757446b0-023b-4745-9727-3488be856c6b.PNG)

**Comment by M-J-Robbins** [comment]
Some screenshots of other implementation

Firefox reader view 
<img width="264" alt="" src="https://user-images.githubusercontent.com/7871206/193284353-9a6d76c1-2b55-4077-be50-4d3449ab84bf.png">

Safari Reader view
![](https://user-images.githubusercontent.com/7871206/193284678-d05a65a4-37ea-488e-a26f-b06e9d1d2413.png)


Chrome reader mode
![](https://user-images.githubusercontent.com/7871206/193285506-afb425bf-d0c5-43a4-abb6-2edfe94ba54d.png)


Reader view extension 
![](https://user-images.githubusercontent.com/7871206/193285905-755c5c6b-2a53-495e-b193-374545c529b9.png)

Reader mode extension
![](https://user-images.githubusercontent.com/7871206/193286021-49421a82-5b19-4afe-9bb4-560c06a69327.png)

**Comment by M-J-Robbins** [comment]
My current thinking on this is having 4 buttons at the top
Light, Dark, Sepia, Disable

These names are placeholders, but the idea is it would give 3 preset style options and an option to remove the reader view.

Below these we could have an option for advanced settings, this will expand to show all the settings we have in the current version but maybe with an updated UI.  When these are changed, they will update the selected preset

**Comment by M-J-Robbins** [comment]
Quick mock up of an idea of a new UI.

* The idea is the use will select one of the 3 style profiles and it will be applied.
* They can click 'customise settings' to adjust the styles in the selected profile.
* If they change the font-family, color, or background-color, these changes will also be reflected in the buttons.
* The user can rename each of the three customisable profiles, as the names may not make sense with the changes they make.
* Clicking 'default' will revert the email back to the original styles it was sent with.

![Email reader view settings. Select your preferred style, showing 4 buttons Light, Dark, Sepia, Default. And an option to Customise settings](https://user-images.githubusercontent.com/7871206/201143347-dafa5399-15f0-4a3c-a49a-142874ef5b50.png)

Please let me know any feedback, thoughts and ideas.
Is there anything missing?
Does this stripped back design work, or should it be a bit prettier? 
Do the button names work? 3 of them are user editable but these would be the default names.
Is the other text ok?

**Comment by theotherstevenc** [comment]
Nice! Preset display options are much needed. 

Allowing the recipient a customized interpretation of `dark`, `sepia` and `light` color contrasts is brilliant. Customizing all options into separate profiles may be excessive. 

Persistent font settings across the various **display styles** is crucial. For example, if a recipient selects a large font, and no margin, each **display style** will want to inherit those settings, _rather than requiring additional input_.

**Firefox** reader view is an ideal model of this experience. A simple approach of usability, with a limited amount of options.

**Comment by M-J-Robbins** [comment]
Closing this as some of the tasks have been completed and others have been broken out into separate issues
