### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by husseinalhammad** [email-markup-consortium/email-reader-view#5]
I think it makes sense to have preset themes instead of asking the user choose text, link and background colours. These granular options can be good to have for "power users" or people who like customising things, but I feel the average user is lazier than that and just wants something that works.

Themes don't have to be just the usual light/dark themes. They can serve purposes too. For example, there can be themes that are optimised for people with certain disabilities such as dyslexia.

**Comment by M-J-Robbins** [comment]
I have a [PR open](https://github.com/email-markup-consortium/email-reader-view/pull/9) with some updates that would give the user 3 default themes to chose from. light, dark, sepia. 

For advanced users these themes are customisable including the theme names.
<img width="370" alt="screen shot of readerview popup" src="https://user-images.githubusercontent.com/7871206/217049788-ce521cc4-2969-43e6-8c07-e2439b99cf04.png">
